package com.bot.middleware.persistence.type;

public enum AwardType {
    STARTER,
    EARLY_USER,
    TEN_TASKS_PERFORMED,
    TEN_TASKS_BIDDER,
    FIFTY_TASKS_PERFORMED,
    FIFTY_TASKS_BIDDER,
    HUNDRED_TASKS_PERFORMED,
    HUNDRED_TASKS_BIDDER,
    SPENT_THOUSAND_DOLLARS,
    EARNED_THOUSAND_DOLLARS,
    SPENT_TEN_THOUSANDS_DOLLARS,
    EARNED_TEN_THOUSANDS_DOLLARS,
    SPENT_MILLION,
    EARNED_MILLION
}
