package com.bot.middleware.persistence.type;

public enum NotificationEnum {
    DEFAULT,
    LOGIN,
    ADDED_BID,
    EDITED_BID,
    DELETED_BID,
    ACCEPTED_BID,
    REJECTED_BID,
    EDITED_TASK,
    RESCHEDULE_TASK_REQUEST,
    RESCHEDULE_TASK_ACCEPTED,
    RESCHEDULE_TASK_REJECTED,
    ASSIGNED_TASK,
    IN_PROGRESS_TASK,
    COMPLETED_TASK,
    FUNDED_TASK,
    PAID_TASK,
    SEND_CHAT,
    VERIFICATION
}
