server:
  ssl:
    key-store: classpath:test.p12
    key-store-type: PKCS12
    key-store-password: test
    enabled: true
  port: 9443

spring:
  datasource:
    driver-class-name:
    url: jdbc:mysql://localhost:3306/users_schema
    username: root
    password:
    dbcp2:
      driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate: org.hibernate.dialect.MySQL8Dialect
      storage_engine: innodb

  mail:
    host: smtp.gmail.com
    port: 587
    username: afinitisami@gmail.com
    password: Testing1234$
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          ssl:
            trust: smtp.gmail.com
          starttls:
            enable: true
            required: true
  liquibase:
    url: jdbc:mysql://localhost:3306/users_schema
    user: root
    password:
    enabled: true
    change-log: db-liquibase/liquibase-changeLog.xml
app:
  auth:
    tokenSecret: 926D270960DDC9429D0358DBBC51AC1B
    tokenExpirationMsec: 259200000
    refreshTokenExpirationMsec: 2592000000
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect


email:
  redirection: https://neighbour.live:9443
  api-key: B0RSG.Abzf8Ozws-lJsrl1NjuWbIvww9j94bWesvysZIYfBg.SlUGaqMovZnAy7qbvmS1
  from: neighbourlivemal@gmail.com

firebase:
  config: confidential/firebase-configuration.json
  database: https://neighbor-live.firebaseio.com